# Source: https://github.com/starkat99/appveyor-rust/

environment:
  global:
    PROJECT_NAME: ffizer
  matrix:
    # Stable channel
    # - TARGET: i686-pc-windows-gnu
    #   MSYS_BITS: 32
    #   CHANNEL: stable
    - TARGET: i686-pc-windows-msvc
      CHANNEL: stable
    # - TARGET: x86_64-pc-windows-gnu
    #   MSYS_BITS: 64
    #   CHANNEL: stable
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
      VCPKG_DEFAULT_TRIPLET: x64-windows-static
      RUSTFLAGS: -Ctarget-feature=+crt-static

# Install Rust and Cargo
# (Based on from https://github.com/rust-lang/libc/blob/master/appveyor.yml)
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS_BITS%\bin;C:\msys64\usr\bin
  - rustc -Vv
  - cargo -V
  - if defined VCPKG_DEFAULT_TRIPLET git clone https://github.com/Microsoft/vcpkg c:\projects\vcpkg
  - if defined VCPKG_DEFAULT_TRIPLET c:\projects\vcpkg\bootstrap-vcpkg.bat
  - if defined VCPKG_DEFAULT_TRIPLET set VCPKG_ROOT=c:\projects\vcpkg
  - if defined VCPKG_DEFAULT_TRIPLET echo yes > %VCPKG_ROOT%\Downloads\AlwaysAllowDownloads
  - if defined VCPKG_DEFAULT_TRIPLET %VCPKG_ROOT%\vcpkg.exe install zlib

# 'cargo test' takes care of building for us, so disable Appveyor's build stage. This prevents
# the "directory does not contain a project or solution file" error.
# source: https://github.com/starkat99/appveyor-rust/blob/master/appveyor.yml#L113
build: false

# Equivalent to Travis' `script` phase
test_script:
  - cargo build --verbose --target %TARGET%
  - cargo test --target %TARGET%
  - cargo run --target %TARGET%

before_deploy:
  # Generate artifacts for release
  - cargo build --release --target %TARGET%
  - mkdir staging
  - copy target\%TARGET%\release\%PROJECT_NAME%.exe staging
  - ps: copy target\%TARGET%\release\build\ffizer*\out\_ffizer.ps1 staging
  - cd staging
    # release zipfile will look like 'rust-everywhere-v1.2.3-x86_64-pc-windows-msvc'
  - 7z a ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip *
  - appveyor PushArtifact ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip

deploy:
  description: 'Windows release'
  # All the zipped artifacts will be deployed
  artifact: /.*\.zip/
  # Here's how:
  # - Go to 'https://github.com/settings/tokens/new' and generate a Token with only the
  # `public_repo` scope enabled
  # - Then go to 'https://ci.appveyor.com/tools/encrypt' and enter the newly generated token.
  # - Enter the "encrypted value" below
  auth_token:
    secure: DN8fOnUQIcnUAI17/OqNfeHDOPmdbhWYoyW268TfSmzcyeSU9XD6zlL+7zUkqIeB
  provider: GitHub
  # deploy when a new tag is pushed and only on the stable channel
  on:
    # channel to use to produce the release artifacts
    CHANNEL: stable
    appveyor_repo_tag: true

branches:
  only:
    - master
    # IMPORTANT Regex to match tags. Required, or appveyor may not trigger deploys when a new tag
    # is pushed. This regex matches semantic versions like v1.2.3-rc4+2016.02.22
    - /^\d+\.\d+\.\d+.*$/

# Disable caching, for now
#cache:
#  - '%USERPROFILE%\.cargo'
#  - 'target -> Cargo.lock'
